### ISSUE TITLE
Before and After Dates + Weather // Calendar Functionality

### ISSUE THREAD

**Issue by lightoftwelve** [lightoftwelve/travel-tracker#1]
# Calendar Functionality with Before and After Dates

## User Story
AS A developer,
I WANT to implement calendar functionality with before and after dates
SO THAT users can plan their activities based on the desired time of year and view corresponding weather information.

## Acceptance Criteria
GIVEN the bucket list app with a calendar feature,
WHEN a user selects a start and end date,
THEN the app should retrieve weather information for the selected dates and display it to the user.

**Comment by ManjiniAbraham** [comment]
This has been implemented.
