### ISSUE TITLE
Historical Weather : Stylize Weather //  // UI UX Design

### ISSUE THREAD

**Issue by lightoftwelve** [lightoftwelve/travel-tracker#12]
# Stylize Weather

## User Story
AS A developer,
I WANT to stylize the weather section of the bucket list app
SO THAT it presents weather information in a visually appealing and easy-to-read format.

## Acceptance Criteria
GIVEN the bucket list app with a weather section,
WHEN a user views the weather information,
THEN it should be presented in a visually pleasing manner, ensuring readability and appropriate use of weather-related icons or visuals.

**Comment by ManjiniAbraham** [comment]
This has been inplemented . when user selects a startdate, historical weather data will be displayed.
