### ISSUE TITLE
Ensure Calendar Functions Correctly // Calendar Functionality

### ISSUE THREAD

**Issue by lightoftwelve** [lightoftwelve/travel-tracker#27]
# Ensure Calendar Functions Correctly

## User Story
AS A developer,
I WANT to ensure that the calendar functions correctly on the bucket list app
SO THAT users can effectively plan and manage their activities.

## Acceptance Criteria
GIVEN the bucket list app with a calendar feature,
WHEN interacting with the calendar,
THEN users should be able to select dates, navigate between months, and view the selected dates accurately.

**Comment by ManjiniAbraham** [comment]
### Acceptance Criteria

- WHEN a user selects start date, the end date should not be beyond the prior range of the start date
- WHEN a user selects the end date before selecting the start date, it should be disabled
- WHEN a user selects the start date from the calendar, the start date input captures the date
- WHEN a user selects the enddate from the calendar, the end date input captures the date
