### ISSUE TITLE
Search Function // Map Functionality

### ISSUE THREAD

**Issue by lightoftwelve** [lightoftwelve/travel-tracker#3]
# Search Function // Map Functionality

## User Story
AS A developer,
I WANT to add a search function to the map functionality
SO THAT users can easily find and select locations for their bucket list items.

## Acceptance Criteria
GIVEN the bucket list app with a map search function,
WHEN a user enters a location in the search input,
THEN the app should automatically fill in the title and address fields on the bucket list dashboard based on the selected location.

**Comment by StanOp09** [comment]
Search function meets acceptance criteria
