### ISSUE TITLE
Ensure  Current Weather Appends Correctly to Retrievable Lists // Weather Functionality // Dashboard Functionality

### ISSUE THREAD

**Issue by lightoftwelve** [lightoftwelve/travel-tracker#30]
# Ensure Weather Appends Correctly to Retrievable Lists

## User Story
AS A developer,
I WANT to ensure that the weather appends correctly to the retrievable lists on the bucket list app
SO THAT users can view and access the weather information for their selected locations.

## Acceptance Criteria
GIVEN the bucket list app with a weather app feature,
WHEN retrieving weather information for selected locations,
THEN the app should append the weather data to the respective lists, ensuring it is displayed correctly and consistently.

**Comment by ManjiniAbraham** [comment]
Functionality implemented. 
updated the following areas:
script.js
//updating weather data based on Long and Lat
// Save to local storage
 //set Lat and Long
mapbox.js
//need to store Long,Lat coordinates of the place
// store the selected places' co-ordinates.
html

**Comment by ManjiniAbraham** [comment]
Current weather retrieval has been implemented . On clicking any city/place from the search list, the coresponding 'current weather' data is retrieved and displayed on the page.
