### ISSUE TITLE
Weather & Map Correspondence // Weather Functionality

### ISSUE THREAD

**Issue by lightoftwelve** [lightoftwelve/travel-tracker#4]
# Weather App Functionality

## User Story
AS A developer,
I WANT to implement weather app functionality
SO THAT users can view weather information for their selected locations.

## Acceptance Criteria
GIVEN the bucket list app with weather app integration,
WHEN a user selects a location,
THEN the app should retrieve and display the weather information for that location.

**Comment by ManjiniAbraham** [comment]
Current weather map feature has been implemented on searching new city/place
